name: chomoi
description: A Flutter Clean Architecture Using GetX.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # A quick and powerful app layout.
  # Supports page state preservation, lazy page loading, and has a page backstack.
  bottom_nav_layout: ^3.0.9
  convex_bottom_bar: ^3.1.0+1

  # State management + dependencies injection + routing
  get: ^4.6.1

  # UI
  flutter_easyloading: ^3.0.3
  flutter_svg: ^1.0.3
  visibility_detector: ^0.3.2
  cupertino_icons: ^1.0.2
  sliver_tools: ^0.2.5
  badges: ^2.0.3
  flutter_staggered_grid_view: ^0.4.1
  photo_view: ^0.14.0
  flutter_chat_bubble: ^2.0.0
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2

  # Services
  connectivity_plus: ^2.2.1
  flutter_secure_storage: ^5.0.2
  get_storage: ^2.0.3

  # Networking
  url_launcher: ^6.1.6
  async: ^2.4.1
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.6

  # Annotation
  json_annotation: ^4.6.0
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0

  # Utils
  jiffy: ^5.0.0
  dartz: ^0.10.1
  intl: ^0.17.0
  currency_text_input_formatter: ^2.1.8

  # Mobile library for Android and iOS that parses Adobe After Effects animations exported as json
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: 'ic_launcher'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/launcher/icon.png'

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/logos/
     - assets/icons/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
