// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQQtOlAhGEudcslxkFqoCO_5s-nFrp078',
    appId: '1:257214432280:web:9a54a8edb60911ebe7af6d',
    messagingSenderId: '257214432280',
    projectId: 'advertising-classified',
    authDomain: 'advertising-classified.firebaseapp.com',
    databaseURL: 'https://advertising-classified-default-rtdb.firebaseio.com',
    storageBucket: 'advertising-classified.appspot.com',
    measurementId: 'G-WHH7TRJVF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGdjPUDTWkcUqS_Pn7K2rUA8-eUXAPB8',
    appId: '1:257214432280:android:ee9c43f60afe9751e7af6d',
    messagingSenderId: '257214432280',
    projectId: 'advertising-classified',
    databaseURL: 'https://advertising-classified-default-rtdb.firebaseio.com',
    storageBucket: 'advertising-classified.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6UKuxcC_GyWrPxiom-siIPD6kafLw9_s',
    appId: '1:257214432280:ios:b039d893947bf88ee7af6d',
    messagingSenderId: '257214432280',
    projectId: 'advertising-classified',
    databaseURL: 'https://advertising-classified-default-rtdb.firebaseio.com',
    storageBucket: 'advertising-classified.appspot.com',
    iosClientId: '257214432280-6p6b7e80jlbb5oab1s2u0638rjumhrer.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxCleanArchitecture',
  );
}
